### ISSUE TITLE
iron-flex-layout is depricated

### ISSUE THREAD

**Issue by 8ctopotamus** [Collaborne/paper-search#16]
I get this error when using paper-search:

```This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead```

It prevents a few of the icons in my site from working as well. Could you update your excellent search element to use iron-flex-layout-classes? Thanks!

**Comment by ronnyroeller** [comment]
@8ctopotamus - Sounds like a good idea. Feel free to provide a PR if you want to get it merged
