### ISSUE TITLE
items search results are not shown on demo

### ISSUE THREAD

**Issue by kmyllyvi** [Collaborne/paper-search#19]
Referring to paper-search-panel demo
https://www.webcomponents.org/element/Collaborne/paper-search/demo/demo/paper-search-panel.html

I see the items array gets initialized with values ["A", "B", "C"] but I see no effect to items value when searching these items. Are these items supposed to be displayed on the panel? Is the search/filtering really working or is the meaning to implement the actual functionality by one self? it's a little bit unclear from the API doc/demo what to actually expect.
To me it looks like either a bug or simply missing documentation on how items array works and is displayed or not displayed, or I just missed something obvious here?
Any insight much appreciated.

**Comment by BorntraegerMarc** [comment]
I'm having the same issue/question

**Comment by ankon** [comment]
The component is intended to show the state of a search operation executed elsewhere. It does get the array of found items by that search, but only looks at the _length_ of that array to determine whether there have been any results or not.

I've tried to make that clearer with 6ab9261.

**Comment by kmyllyvi** [comment]
Okay, thanks for the prompt reply. That does clarify, thanks. I will make my trials based on this.
