### ISSUE TITLE
Polymer 2 support?

### ISSUE THREAD

**Issue by BorntraegerMarc** [Collaborne/paper-search#20]
Will this component be polymer 2.0+ compatible?

**Comment by BorntraegerMarc** [comment]
Friendly ping to @ronnyroeller & @ankon :) Now maybe would be a good time to make the component to v2.0 as Polymer 2 final is released...

**Comment by ankon** [comment]
Now that Polymer 2.0 is released this seems sensible indeed :)

We currently have not scheduled the work though, and it might take a while -- our application is fairly big, so migrating to Polymer 2.0 is not just a small thing. Likely we'll hold of until the CLI tools for migration are available.

Obviously if you can test this with Polymer 2.0 and provide a PR, then we should try to merge that in! :)

**Comment by BorntraegerMarc** [comment]
Maybe we can run it in hybrid mode? I think the API stayed the same - shouldn't be a too bit of an issue. I may take a look

**Comment by BorntraegerMarc** [comment]
Solved with https://github.com/Collaborne/paper-search/pull/21
