### ISSUE TITLE
"hidden" property not working

### ISSUE THREAD

**Issue by stemuk** [Collaborne/paper-search#25]
Under Polymer 2.0 the hidden property doesn't seem to work. I tested this under the latest Polymer Version in the Chrome and Firefox Browsers. 
Example:

`<paper-search-bar hidden></paper-search-bar>`

**Comment by ronnyroeller** [comment]
This is related to Polymer 2.0.
See: https://github.com/Polymer/polymer/issues/3711#issuecomment-226361758
