### ISSUE TITLE
'paper-search-panel` Provide data to search

### ISSUE THREAD

**Issue by dbrownjave** [Collaborne/paper-search#31]
I don’t know how to search through an array and display the results. 
How do I provide my array, so I can search through it?

Any help appreciated. 

<img width="669" alt="screen shot 2018-02-07 at 11 56 13 pm" src="https://user-images.githubusercontent.com/19171147/35987646-43a660c2-0cca-11e8-94a3-2d515d7f2eb9.png">

**Comment by ronnyroeller** [comment]
The `<paper-search-panel>` doesn't take care of searching itself.
It exposes the `search` property with the search term (see https://github.com/Collaborne/paper-search/blob/master/demo/paper-search-panel.html#L32).
Your application needs to use the search term to do its magic (like send a query to your search backend or do some filtering in the frontend).
