### ISSUE TITLE
paper-filter-dialog: Iron-list gets saved on closing via 'X' button

### ISSUE THREAD

**Issue by TheSPD** [Collaborne/paper-search#6]
The iron-list component which shows all the possible values for the filter retains values even when it is closed via the 'X'(Not save filters).

To replicate the issue try this in the [demo](http://collaborne.github.io/paper-search/components/paper-search/#paper-filter-dialog) 

Select Age -> select 0-12 -> Back and exit with 'X'
If dialog is opened again, Age list still shows 0-12 selected.

**Comment by ronnyroeller** [comment]
Thanks a lot for reporting the issue, @TheSPD 
Feel free to provide a PR an I will merge it.
